export const ADMIN_ROUTE = '/admin'
export const CATALOG_ROUTE = '/catalog'
export const ITEM_ROUTE = '/item'
export const BASKET_ROUTE = '/basket'
export const CONSTRUCTOR_ROUTE = '/constructor'
export const MAIN_ROUTE = '/'
